// SPDX-License-Identifier: BSD-3-Clause

package xpath

import (
	"bufio"
	"encoding/json"
	"os"
	"testing"
)

// oracleCase is one line of testdata/cases.jsonl / oracle-pv2.jsonl
// (generated by TestOracleLive -update, build tag oracle).
type oracleCase struct {
	Set   string          `json:"set,omitempty"`
	CP    string          `json:"cp"`
	X     string          `json:"x"`
	Res   json.RawMessage `json:"result,omitempty"`
	Error json.RawMessage `json:"error,omitempty"` // {"err","vecode","msg"} of the first error diagnostic
	Crash bool            `json:"crash,omitempty"` // lyoracle died (libyang crashed)
}

func readCases(t *testing.T, name string) []oracleCase {
	f, err := os.DirFS("testdata").Open(name)
	if err != nil {
		t.Fatal(err)
	}
	defer func() { _ = f.Close() }()
	var cs []oracleCase
	sc := bufio.NewScanner(f)
	sc.Buffer(nil, 1<<24)
	for sc.Scan() {
		var c oracleCase
		if err := json.Unmarshal(sc.Bytes(), &c); err != nil {
			t.Fatal(err)
		}
		cs = append(cs, c)
	}
	return cs
}

func replay(t *testing.T, cases []oracleCase) { replayCompile(t, cases) }
