// SPDX-License-Identifier: BSD-3-Clause

package xpath

import (
	"bufio"
	"encoding/json"
	"errors"
	"maps"
	"math"
	"os"
	"slices"
	"strconv"
	"strings"
	"testing"
)

// oracleCase is one line of testdata/cases.jsonl / oracle-pv2.jsonl
// (generated by TestOracleLive -update, build tag oracle).
type oracleCase struct {
	Arch  string          `json:"arch,omitempty"` // header line: GOARCH of the generator
	Set   string          `json:"set,omitempty"`
	CP    string          `json:"cp"`
	X     string          `json:"x"`
	Res   json.RawMessage `json:"result,omitempty"`
	Error json.RawMessage `json:"error,omitempty"` // {"err","vecode","msg"} of the first error diagnostic
	Crash bool            `json:"crash,omitempty"` // lyoracle died (libyang crashed, D-0012)
	// Vars are the request's variables; lyoracle receives them as a JSON object, keys sorted.
	Vars map[string]string `json:"vars,omitempty"`
}

// vars is c.Vars in the order lyoracle sets them (JSON object keys, sorted).
func (c oracleCase) vars() []Var {
	var vs []Var
	for _, k := range slices.Sorted(maps.Keys(c.Vars)) {
		vs = SetVar(vs, k, c.Vars[k])
	}
	return vs
}

func readCases(t *testing.T, name string) []oracleCase {
	f, err := os.DirFS("testdata").Open(name)
	if err != nil {
		t.Fatal(err)
	}
	defer func() { _ = f.Close() }()
	var cs []oracleCase
	sc := bufio.NewScanner(f)
	sc.Buffer(nil, 1<<24)
	for sc.Scan() {
		var c oracleCase
		if err := json.Unmarshal(sc.Bytes(), &c); err != nil {
			t.Fatal(err)
		}
		if c.Arch != "" { // header line of oracle-pv2.jsonl
			if c.Arch != oracleArch {
				t.Fatalf("%s was generated on %s, the canonical oracle is %s", name, c.Arch, oracleArch)
			}
			continue
		}
		cs = append(cs, c)
	}
	return cs
}

// oracleArch is where canonical libyang results come from (long double width).
const oracleArch = "amd64"

// knownDiff lists oracle cases we intentionally do not reproduce.
var knownDiff = map[string]string{}

// crashAnswers are the defined results we give where libyang crashes (D-0012):
// a result JSON, or "error: <message>".
var crashAnswers = map[string]string{
	"deref(..)":                 `{"type":"node-set","nodes":[]}`,
	"bit-is-set(.., 'x')":       `{"type":"boolean","value":false}`,
	"enum-value(..)":            `{"type":"number","value":"NaN"}`,
	"derived-from(c/id, 'one')": `error: Identity "one" not found in module "".`,
	"string(any)":               `{"type":"string","value":""}`,
	"string(.)":                 `{"type":"string","value":"\n"}`,
}

func replay(t *testing.T, cases []oracleCase) {
	replayCompile(t, cases)
	for _, c := range cases {
		if knownDiff[c.X] != "" {
			continue
		}
		tree, schema := pv2Tree(), SchemaInfo(nil)
		switch c.Set {
		case "union":
			tree = unionTree()
		case "aug":
			tree = augTree()
		case "anydata":
			tree = top(cont("pv2:c", mk(KindAnydata, "any", &tval{})))
		}
		schema = tinfo{tree: tree}
		ec := EvalContext{Tree: tree, IgnoreWhen: true, Schema: schema, Deref: pv2Deref(tree), Vars: c.vars()}
		if c.CP != "" {
			ec.Node = tree[0]
		}
		res, err := eval(c.X, ec)
		switch {
		case c.Crash: // D-0012: our documented answer
			want, ok := crashAnswers[c.X]
			switch {
			case !ok:
				t.Errorf("%q: libyang crashes, add the answer to crashAnswers and D-0012", c.X)
			case strings.HasPrefix(want, "error: "):
				if err == nil || err.Error() != strings.TrimPrefix(want, "error: ") {
					t.Errorf("%q (crash case): want %s, got %v", c.X, want, err)
				}
			default:
				if msg := sameResult(json.RawMessage(want), res, err); msg != "" {
					t.Errorf("%q (crash case): %s", c.X, msg)
				}
			}
		case c.Error == nil:
			if msg := sameResult(c.Res, res, err); msg != "" {
				t.Errorf("%q (%s): %s", c.X, c.Set, msg)
			}
		default:
			var want struct{ Err, Vecode string }
			_ = json.Unmarshal(c.Error, &want)
			var raw struct{ Msg json.RawMessage }
			_ = json.Unmarshal(c.Error, &raw)
			msg := jsonString(raw.Msg)
			var xe *Error
			if !errors.As(err, &xe) {
				t.Errorf("%q: want error %q, got %v (err %v)", c.X, msg, res, err)
				continue
			}
			vecode := xe.VECode
			if vecode == "" {
				vecode = "LYVE_SUCCESS"
			}
			msgOK := xe.Msg == msg || strings.HasPrefix(c.X, "re-match") // PCRE2 vs XSD error detail
			if xe.Err != want.Err || vecode != want.Vecode || !msgOK {
				t.Errorf("%q: want %s %s %q, got %s %s %q", c.X, want.Err, want.Vecode, msg, xe.Err, vecode, xe.Msg)
			}
		}
	}
}

// sameResult compares with lyoracle's result JSON: strings byte for byte,
// numbers by value, node-sets by data path.
func sameResult(raw json.RawMessage, r Result, err error) string {
	var want struct {
		Type  string
		Value json.RawMessage
		Nodes []string
	}
	_ = json.Unmarshal(raw, &want)
	got := ""
	switch r.Type {
	case Boolean:
		got = "boolean " + strconv.FormatBool(r.Bool)
		if string(want.Value) != strconv.FormatBool(r.Bool) {
			return "want " + string(raw) + ", got " + got
		}
	case String:
		if jsonString(want.Value) != r.Str {
			return "want " + string(raw) + ", got string " + strconv.Quote(r.Str)
		}
	case Number:
		var w any
		_ = json.Unmarshal(want.Value, &w)
		ok := false
		switch w := w.(type) {
		case float64:
			ok = w == r.Num
		case string:
			ok = w == "NaN" && math.IsNaN(r.Num) || w == "Infinity" && math.IsInf(r.Num, 1) || w == "-Infinity" && math.IsInf(r.Num, -1)
		}
		if !ok {
			return "want " + string(raw) + ", got number " + strconv.FormatFloat(r.Num, 'g', -1, 64)
		}
	default:
		var ps []string
		for _, n := range r.Nodes {
			ps = append(ps, path(n))
		}
		if strings.Join(ps, " ") != strings.Join(want.Nodes, " ") {
			return "want " + string(raw) + ", got " + strings.Join(ps, " ")
		}
	}
	if err != nil || want.Type != [...]string{"node-set", "boolean", "number", "string"}[r.Type] {
		return "want " + string(raw) + ", got error " + errString(err)
	}
	return ""
}

func errString(err error) string {
	if err == nil {
		return "<nil>"
	}
	return err.Error()
}

// jsonString decodes a cJSON string literal keeping raw bytes (cJSON does not
// escape bytes >= 0x80, which need not be valid UTF-8).
func jsonString(raw json.RawMessage) string {
	s := strings.TrimSuffix(strings.TrimPrefix(string(raw), `"`), `"`)
	var b strings.Builder
	for i := 0; i < len(s); i++ {
		if s[i] != '\\' || i+1 >= len(s) {
			b.WriteByte(s[i])
			continue
		}
		i++
		switch c := s[i]; c {
		case 'b':
			b.WriteByte('\b')
		case 'f':
			b.WriteByte('\f')
		case 'n':
			b.WriteByte('\n')
		case 'r':
			b.WriteByte('\r')
		case 't':
			b.WriteByte('\t')
		case 'u':
			if v, err := strconv.ParseInt(s[i+1:min(i+5, len(s))], 16, 32); err == nil {
				b.WriteRune(rune(v))
				i += 4
			}
		default:
			b.WriteByte(c)
		}
	}
	return b.String()
}
