// SPDX-License-Identifier: BSD-3-Clause

package xpath

import (
	"fmt"
	"regexp"
	"strconv"
	"strings"
	"testing"
)

var digits = regexp.MustCompile(`^[0-9]+$`)

// intCheck is the store message libyang gives a value of the unsigned or signed type name.
func intCheck(name string, limit int) func(string) (string, bool) {
	return func(v string) (string, bool) {
		n, err := strconv.Atoi(v)
		switch {
		case !digits.MatchString(v):
			return fmt.Sprintf("Invalid type %s value \"%s\".", name, v), false
		case err != nil || n > limit:
			return fmt.Sprintf("Value \"%s\" is out of type %s min/max bounds.", v, name), false
		}
		return "", true
	}
}

func enumCheck(names ...string) func(string) (string, bool) {
	return func(v string) (string, bool) {
		for _, n := range names {
			if n == v {
				return "", true
			}
		}
		return fmt.Sprintf("Invalid enumeration value \"%s\".", v), false
	}
}

func (s *tschema) checked(n string, k Kind, t *ttype, check func(string) (string, bool)) *tschema {
	return s.add(&tschema{kind: k, mod: s.mod, name: n, config: true, typ: t, check: check})
}

// TestEqualityValue: tokens, sides, error variants and trailer of warn_equality_value.
func TestEqualityValue(t *testing.T) {
	top := newTop("m")
	var checked []string
	rec := func(msg string, ok bool) func(string) (string, bool) {
		return func(v string) (string, bool) { checked = append(checked, v); return msg, ok }
	}
	top.checked("bad", KindLeaf, bt(TypeUint8), rec("boom", false))
	top.checked("nomsg", KindLeaf, bt(TypeUint8), rec("", false))
	top.checked("fine", KindLeaf, bt(TypeUint8), rec("", true))
	top.checked("ll", KindLeafList, bt(TypeUint8), rec("boom", false))
	top.checked("id", KindLeaf, bt(TypeIdent), rec("", false))
	top.add(&tschema{kind: KindContainer, mod: "m", name: "c", config: true})
	cur := `with context node "/m:top".`
	for _, c := range []struct {
		x       string
		want    []string
		checked string
	}{
		{"bad = 12", []string{`Invalid value "12" which does not fit the type (boom).`,
			`Previous warning generated by XPath subexpression[0] "bad = 12" ` + cur}, "12"}, // number text verbatim
		{"bad = '  a b '", []string{`Invalid value "  a b " which does not fit the type (boom).`,
			`Previous warning generated by XPath subexpression[0] "bad = '  a b '" ` + cur}, "  a b "}, // literal without its quotes
		{"'x' != bad", []string{`Invalid value "x" which does not fit the type (boom).`,
			`Previous warning generated by XPath subexpression[0] "'x' != bad" ` + cur}, "x"}, // left token, right set
		{"nomsg = 1", []string{`Invalid value "1" which does not fit the type.`,
			`Previous warning generated by XPath subexpression[0] "nomsg = 1" ` + cur}, "1"},
		{"ll = 5", []string{`Invalid value "5" which does not fit the type (boom).`,
			`Previous warning generated by XPath subexpression[0] "ll = 5" ` + cur}, "5"},
		{"fine = 5 and nomsg", nil, "5"},
		{"bad = bad", nil, ""}, // no literal or number token
		{"c = 5", []string{`Node type container "c" used as operand.`, `Previous warning generated by XPath subexpression[0] "c = 5" ` + cur}, ""},
		{"bad < 5", nil, ""}, // only = and !=
		{"1 = 2", nil, ""},   // no node
		{"id = 'der'", []string{`Identityref "id" comparison with identity "der" without prefix, consider adding a prefix or best using "derived-from(-or-self)()" functions.`,
			`Previous warning generated by XPath subexpression[0] "id = 'der'" ` + cur}, ""},
		{"id = 'm:der'", nil, ""}, // prefixed: no warning and no store
		// libyang: the right token is the LAST token of the right operand; the trailer starts at the
		// token before the operator and ends at that last token
		{"fine = (1 + bad) = 3", nil, ""}, // the first = left the set out of context
		{"bad = 1 + 2", []string{`Invalid value "2" which does not fit the type (boom).`,
			`Previous warning generated by XPath subexpression[0] "bad = 1 + 2" ` + cur}, "2"},
	} {
		checked = nil
		got := warnsOf(t, top, []string{c.x})
		if strings.Join(got, "\n") != strings.Join(c.want, "\n") {
			t.Errorf("%q:\ngot  %q\nwant %q", c.x, got, c.want)
		}
		if strings.Join(checked, "|") != strings.Join(strings.FieldsFunc(c.checked, func(r rune) bool { return r == '|' }), "|") {
			t.Errorf("%q: checked %q, want %q", c.x, checked, c.checked)
		}
	}
}
