// SPDX-License-Identifier: BSD-3-Clause
// Ported from libyang v5.8.6 src/xpath.c (warn_get_scnode_in_ctx, warn_is_numeric_type,
// warn_is_string_type, warn_is_specific_type, warn_is_equal_type_next_type, warn_is_equal_type,
// warn_subexpr_log, warn_operands) and src/tree_schema_common.c (lys_nodetype2str)
// (BSD-3-Clause, © CESNET).

package xpath

import (
	"fmt"
	"strings"
)

// isNumericType is warn_is_numeric_type: an integer or decimal64 type, a union with such a member
// or a leafref to one.
func isNumericType(t SchemaType) bool {
	switch t.Base() {
	case TypeDec64, TypeInt8, TypeUint8, TypeInt16, TypeUint16, TypeInt32, TypeUint32, TypeInt64, TypeUint64:
		return true
	case TypeUnion:
		for _, m := range t.Union() {
			if isNumericType(m) {
				return true
			}
		}
	case TypeLeafref:
		return isNumericType(t.Realtype())
	}
	return false
}

// isStringType is warn_is_string_type: bits, enumeration, identityref, instance-identifier or
// string, also as a union member or behind a leafref.
func isStringType(t SchemaType) bool {
	switch t.Base() {
	case TypeBits, TypeEnum, TypeIdent, TypeInst, TypeString:
		return true
	case TypeUnion:
		for _, m := range t.Union() {
			if isStringType(m) {
				return true
			}
		}
	case TypeLeafref:
		return isStringType(t.Realtype())
	}
	return false
}

// isSpecificType is warn_is_specific_type: t, a union member or a leafref target has base type b.
func isSpecificType(t SchemaType, b BaseType) bool {
	switch t.Base() {
	case b:
		return true
	case TypeUnion:
		for _, m := range t.Union() {
			if isSpecificType(m, b) {
				return true
			}
		}
	case TypeLeafref:
		return isSpecificType(t.Realtype(), b)
	}
	return false
}

// flatMembers appends the members warn_is_equal_type_next_type yields for t, in order: a leafref is
// followed to its realtype, a union recursed, anything else is a member.
func flatMembers(t SchemaType, out []SchemaType) []SchemaType {
	if t.Base() == TypeLeafref {
		t = t.Realtype()
	}
	if t.Base() != TypeUnion {
		return append(out, t)
	}
	for _, m := range t.Union() {
		out = flatMembers(m, out)
	}
	return out
}

// equalType is warn_is_equal_type: some member of t1 has the base type of some member of t2.
// libyang resumes its walk after the previous member found by pointer identity
// (warn_is_equal_type_next_type), so a union that repeats one type object makes it cycle forever
// whenever no base matches (D-0015). This walks the flattened members by index instead: the same
// answer whenever libyang terminates, and it terminates.
func equalType(t1, t2 SchemaType) bool {
	m2 := flatMembers(t2, nil)
	for _, x := range flatMembers(t1, nil) {
		for _, y := range m2 {
			if x.Base() == y.Base() {
				return true
			}
		}
	}
	return false
}

// kindStr is lys_nodetype2str: input and output are "unknown" there.
func kindStr(k Kind) string {
	switch k {
	case KindContainer:
		return "container"
	case KindChoice:
		return "choice"
	case KindLeaf:
		return "leaf"
	case KindLeafList:
		return "leaf-list"
	case KindList:
		return "list"
	case KindAnyxml:
		return "anyxml"
	case KindAnydata:
		return "anydata"
	case KindCase:
		return "case"
	case KindRPC:
		return "RPC"
	case KindAction:
		return "action"
	case KindNotif:
		return "notification"
	}
	return "unknown"
}

// warnSubexpr is warn_subexpr_log: 20 bytes of the expression from tokPos (C "%.*s" stops at the
// end of the string), with the path of the expression's context node ("/" when it is the root).
func (a *atomizer) warnSubexpr(tokPos int) {
	sub := a.src[min(tokPos, len(a.src)):]
	if len(sub) > 20 {
		sub = sub[:20]
	}
	a.warnSubexprText(tokPos, sub)
}

func (a *atomizer) warnSubexprText(tokPos int, sub string) {
	cur := "/"
	if a.cur != nil {
		cur = a.cur.Path()
	}
	a.warn(fmt.Sprintf("Previous warning generated by XPath subexpression[%d] \"%s\" with context node \"%s\".", tokPos, sub, cur))
}

// warnOperands is warn_operands: the operands of an operator, as the last node in context of each
// set (s2 nil for the unary minus), checked for node type and, with numbersOnly, for a numeric
// type; without it two leaves must have compatible types. tokPos is the offset libyang names the
// subexpression by.
func (a *atomizer) warnOperands(s1, s2 *scset, numbersOnly bool, tokPos int) {
	if a.warn == nil {
		return
	}
	n1 := lastCtx(s1)
	var n2 SchemaNode
	if s2 != nil {
		n2 = lastCtx(s2)
	}
	if n1 == nil && n2 == nil {
		return
	}
	leaves, warning := true, false
	check := func(n SchemaNode) {
		if n == nil {
			return
		}
		switch k := n.Kind(); {
		case k != KindLeaf && k != KindLeafList:
			a.warn(fmt.Sprintf("Node type %s \"%s\" used as operand.", kindStr(k), n.Name()))
			warning, leaves = true, false
		case numbersOnly && !isNumericType(n.Type()):
			a.warn(fmt.Sprintf("Node \"%s\" is not of a numeric type, but used where it was expected.", n.Name()))
			warning = true
		}
	}
	check(n1)
	check(n2)
	if n1 != nil && n2 != nil && leaves && !numbersOnly {
		num1, num2 := isNumericType(n1.Type()), isNumericType(n2.Type())
		if num1 != num2 || (!num1 && !equalType(n1.Type(), n2.Type())) {
			a.warn(fmt.Sprintf("Incompatible types of operands \"%s\" and \"%s\" for comparison.", n1.Name(), n2.Name()))
			warning = true
		}
	}
	if warning {
		a.warnSubexpr(tokPos)
	}
}

// warnEqualityValue is warn_equality_value: when the last node in context of s is a leaf or
// leaf-list and val is a Literal or Number token, the token's text must fit the node's type. The
// trailer spans from the token eq to the end of the token last. libyang's token arguments (the
// token before the operator and the last token of the right operand) are passed as they are, so
// `n = 1 + 2` checks "2" against n.
func (a *atomizer) warnEqualityValue(s *scset, val, eq, last token) {
	n := lastCtx(s)
	if n == nil || a.warn == nil || (n.Kind() != KindLeaf && n.Kind() != KindLeafList) || (val.k != tLiteral && val.k != tNumber) {
		return
	}
	value := a.src[val.pos : val.pos+val.len]
	if val.k == tLiteral {
		value = value[1 : len(value)-1]
	}
	trailer := func() { a.warnSubexprText(eq.pos, a.src[eq.pos:last.pos+last.len]) }
	if n.Type().Base() == TypeIdent {
		if !strings.Contains(value, ":") {
			a.warn(fmt.Sprintf("Identityref \"%s\" comparison with identity \"%s\" without prefix, consider adding"+
				" a prefix or best using \"derived-from(-or-self)()\" functions.", n.Name(), value))
			trailer()
		}
		return
	}
	msg, ok := n.CheckValue(value, a.ns)
	if ok {
		return
	}
	if msg != "" {
		a.warn(fmt.Sprintf("Invalid value \"%s\" which does not fit the type (%s).", value, msg))
	} else {
		a.warn(fmt.Sprintf("Invalid value \"%s\" which does not fit the type.", value))
	}
	trailer()
}
