//go:build ignore

// SPDX-License-Identifier: BSD-3-Clause

// gen_blocks downloads Unicode Blocks.txt for the Unicode version of the Go
// toolchain's unicode package (so \p{IsX} and \p{Lu} come from one Unicode
// edition) and writes blocks_table.go.
//
// Usage: go generate ./internal/xsdre   (or: go run gen_blocks.go [Blocks.txt])
package main

import (
	"bufio"
	"bytes"
	"fmt"
	"go/format"
	"io"
	"log"
	"net/http"
	"os"
	"strconv"
	"strings"
	"unicode"
)

func main() {
	var src io.Reader
	if len(os.Args) > 1 {
		f, err := os.Open(os.Args[1])
		if err != nil {
			log.Fatal(err)
		}
		defer f.Close()
		src = f
	} else {
		url := "https://www.unicode.org/Public/" + unicode.Version + "/ucd/Blocks.txt"
		resp, err := http.Get(url)
		if err != nil {
			log.Fatal(err)
		}
		defer resp.Body.Close()
		if resp.StatusCode != 200 {
			log.Fatalf("%s: %s", url, resp.Status)
		}
		src = resp.Body
	}

	var body bytes.Buffer
	sc := bufio.NewScanner(src)
	header, copyright := "", ""
	n := 0
	for sc.Scan() {
		line := sc.Text()
		if header == "" && strings.HasPrefix(line, "# Blocks-") {
			header = strings.TrimPrefix(line, "# ")
		}
		if copyright == "" && strings.HasPrefix(line, "# © ") {
			copyright = strings.TrimPrefix(line, "# ")
		}
		if i := strings.IndexByte(line, '#'); i >= 0 {
			line = line[:i]
		}
		rng, name, ok := strings.Cut(line, ";")
		if !ok {
			continue
		}
		lo, hi, ok := strings.Cut(strings.TrimSpace(rng), "..")
		if !ok {
			log.Fatalf("bad line %q", line)
		}
		l, err1 := strconv.ParseUint(lo, 16, 32)
		h, err2 := strconv.ParseUint(hi, 16, 32)
		if err1 != nil || err2 != nil {
			log.Fatalf("bad range %q", rng)
		}
		fmt.Fprintf(&body, "\t%q: {0x%04X, 0x%04X},\n", strings.ReplaceAll(strings.TrimSpace(name), " ", ""), l, h)
		n++
	}
	if err := sc.Err(); err != nil {
		log.Fatal(err)
	}
	if want := "Blocks-" + unicode.Version + ".txt"; header != want {
		log.Fatalf("Blocks.txt header %q, want %q", header, want)
	}
	if copyright == "" {
		log.Fatal("Blocks.txt has no \"# © …\" copyright line")
	}
	// The table is Unicode data: carry its copyright and license (Unicode License V3, full
	// text in NOTICE) next to it.
	var out bytes.Buffer
	fmt.Fprintf(&out, `// SPDX-License-Identifier: BSD-3-Clause AND Unicode-3.0
// Code generated by gen_blocks.go from Unicode %[1]s Blocks.txt; DO NOT EDIT.
//
// The block ranges are data from the Unicode Character Database, %[2]s:
// %[3]s Distributed under the Unicode License V3
// (https://www.unicode.org/license.txt); the full copyright and permission notice is in
// NOTICE in this directory.

package xsdre

// blocksUnicodeVersion is the Unicode edition of Blocks.txt used for this table.
const blocksUnicodeVersion = %[1]q

// blocks maps an XSD block name (Unicode block name with spaces removed) to its range.
var blocks = map[string][2]rune{
`, unicode.Version, header, copyright)
	out.Write(body.Bytes())
	out.WriteString("}\n")
	b, err := format.Source(out.Bytes())
	if err != nil {
		log.Fatal(err)
	}
	if err := os.WriteFile("blocks_table.go", b, 0o644); err != nil {
		log.Fatal(err)
	}
	log.Printf("wrote %d blocks (Unicode %s)", n, unicode.Version)
}
